fs: 44100
win_size: 2048
hop_size: 1024
subsampling: 12
target_smear: 6
class_balance: 0.2
input_shape: [116, 80, 1]
input_data: ['jsd_features', 'salami_features', ]
target_data: ['jsd_targets', 'salami_targets', ]
split_data: ['../../splits/jsd_fold-0.yml', 'data/salami_split.yml']
