name: jsd

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.6.7
    - numpy
    - pandas
    - matplotlib
    - tqdm
    - seaborn
    - scikit-learn
    - yaml
    - pip:
        - mir-eval==0.5
